# -*- mode: ruby -*-
# # vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

# VIP: 192.168.20.150
VAGRANTFILE_API_VERSION = "2"

boxes = [
  {
    :name => "etcd-1",
    :eth1 => "192.168.20.151",
    :mem => "2048",
    :cpu => "1"
  },
  {
    :name => "etcd-2",
    :eth1 => "192.168.20.152",
    :mem => "2048",
    :cpu => "1"
  },
  {
    :name => "etcd-3",
    :eth1 => "192.168.20.153",
    :mem => "2048",
    :cpu => "1"
  },
  {
    :name => "master-1",
    :eth1 => "192.168.20.154",
    :mem => "4096",
    :cpu => "2"
  },
  {
    :name => "master-2",
    :eth1 => "192.168.20.155",
    :mem => "4096",
    :cpu => "2"
  },
  {
    :name => "master-3",
    :eth1 => "192.168.20.156",
    :mem => "4096",
    :cpu => "2"
  },
  {
    :name => "node-1",
    :eth1 => "192.168.20.157",
    :mem => "4096",
    :cpu => "2"
  },
  {
    :name => "node-2",
    :eth1 => "192.168.20.158",
    :mem => "4096",
    :cpu => "2"
  },

]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  # Turn off shared folders
  #config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
  #config.vm.synced_folder "~/works/codelab/cka/files", "/files"
  # config.ssh.private_key_path = "~/.ssh/id_rsa"
  # config.ssh.forward_agent = true

  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.ssh.insert_key = true
      # config.ssh.username = 'vagrant'
      # config.ssh.password = "vagrant"
      # config.vm.provision "shell", inline: $script
      config.vm.provider "virtualbox" do |v|
        # v.gui = true
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end
      # config.vm.network :public_network
      config.vm.network "private_network", ip: opts[:eth1], auto_config: true
    end
  end
end