---
- hosts:
  - masters
  remote_user: vagrant
  become: true
  tasks:
# 1. 集群及节点状态检测
# 1.1 kubeadm 信息查看
# 1.2 集群健康状态检测
# 1.3 节点 Ready 状态检测
  - name: 1.1 kubeadm 信息查看
    shell: kubeadm config view
    register: config
  - name: print kubeadm config
    debug:
      msg: "{{ config.stdout_lines }}"
  
  - name: 1.2 集群健康状态检测
    shell: kubectl get cs |grep 'Unhealthy'
    register: cluster_result
    ignore_errors: true
  - name: print cluster_result
    debug:
      msg: "{{ cluster_result.stdout_lines }}"
      # msg: "{{ cluster_result.stderr_lines }}" 
  - name: 1.3 节点 Ready 状态检测
    shell: kubectl get node|grep -v Ready
    register: node_result
    ignore_errors: true
  - name: print node_result
    debug:
      msg: "{{ node_result.stdout_lines }}"
# 2. 应用状态检测
# 2.1 异常应用检测
  - name: 2.1 异常应用检测
    shell: kubectl get po --all-namespaces -o wide|grep -v Running
    register: pod_result
  - name: print pod_result
    debug:
      msg: "{{ pod_result.stdout_lines }}"
# 3. 集群网络检测
# 3.1 POD 网络连通性检测
  - name: 4.1 POD 网络连通性检测
    shell: nmap -v -sP --unprivileged `kubectl get pods --all-namespaces -o wide | awk  '/Running/{ print $7 }'` | tee /tmp/ping_result
  - name: 4.2 过滤有问题节点
    shell: nmap -v -sP --unprivileged `cat /tmp/ping_result | grep down | awk '{ print $5 }'`
    register: ping_result
  - name: nmap ping_result
    debug:
      msg: "{{ ping_result.stdout_lines }}"
