---
- hosts: 
  - nodes
  remote_user: vagrant
  become: true
  tasks:
# yum install sysstat 
# 1.1 磁盘使用空间大于80
# 1.2 CPU 使用率
# 1.3 内存 负载检测
# 1.4 IO 负载检测
# 1.5 不可中断的进程检测
# 1.6 僵尸进程检测
# 1.7 查看 Kill 的进程
# 1.8 容器内核 BUG 检测
  # - name: 1 准备测试软件
  #   shell: yum install sysstat -y
  - name: 1.1 磁盘使用空间大于80
    shell: df -h|awk '$5 >80' 
    register: disk_result
  - name: print disk result
    debug:
      msg: "{{ disk_result.stdout_lines }}"

  - name: 1.2 CPU 使用率
    shell: top -n 1 -d 1|awk '/%Cpu/{printf("%.2f%\n",(100-$8))}'
    register: cpu_result
  - name: print cpu info
    debug:
      msg: "{{ cpu_result.stdout_lines }}"

  - name: 1.3 内存使用率
    shell: free|awk '/Mem:/{printf("%.2f%\n",($2-$4)/$2*100)}'
    register: mem_result
  - name: print mem info
    debug:
      msg: "{{ mem_result.stdout_lines }}"

  # - name: 1.4 磁盘每秒传输次数-TPS
  #   shell: iostat -d
  - name: 1.5 不可中断的进程检测
    shell: ps auxH|grep " D " 
    register: psD_result
  - name: print psD info
    debug:
      msg: "{{ psD_result.stdout_lines }}"

  - name: 1.6 查看 Kill 的进程
    shell: dmesg |grep Kill
    register: psKill_result
    ignore_errors: true
  - name: print psKill info
    debug:
      msg: "{{ psKill_result.stdout_lines }}"

  - name: 1.7 容器内核 BUG 检测
    shell: dmesg |grep unregister_netdevice
    register: kernel_result
    ignore_errors: true
  - name: print dmesg unregister
    debug:
      msg: "{{ kernel_result.stdout_lines }}"

  - name: 1.8 僵尸进程检测
    shell: ps aux | awk '{ print $8 " " $2 " " $11}' | grep -w Z
    register: psK_result
    ignore_errors: true
  - name: print psK info
    debug:
      msg: "{{ psK_result.stdout_lines }}"

#   - name: 1.9 批量删除僵尸进程
#     shell: ps aux | awk '{ print $8 " " $2}' | grep -w Z|awk '{print $2}'|xargs kill -9